--Q1
--List names of pilots who have flown the most miles
SELECT	E.EMP_FNAME
FROM	CHARTER_FACT CF
			INNER JOIN EMPLOYEE E ON CF.EMP_NUM = E.EMP_NUM INNER JOIN 
			PILOT P ON CF.EMP_NUM = P.EMP_NUM INNER JOIN
			MODEL M ON CF.MOD_CODE = M.MOD_CODE INNER JOIN
			AIRCRAFT A ON M.MOD_CODE = A.MOD_CODE INNER JOIN
			CHARTER C ON A.AC_NUMBER = C.AC_NUMBER
WHERE		C.CHAR_DISTANCE = (SELECT	MAX(CHAR_DISTANCE)
							   FROM		CHARTER)

--Q2
--List revenue by model and month in ascending order
SELECT	REVENUE
FROM	CHARTER_FACT CF 
			INNER JOIN MODEL M ON CF.MOD_CODE = M.MOD_CODE INNER JOIN
			AIRCRAFT A ON M.MOD_CODE = A.MOD_CODE INNER JOIN
			CHARTER C ON A.AC_NUMBER = C.AC_NUMBER
ORDER BY	M.MOD_CODE, MONTH(C.CHAR_DATE)