/* A10 Script */

CREATE TABLE CUSTOMERDIM (
CUS_CODE int NOT NULL IDENTITY,
CUS_LNAME varchar(15),
CUS_FNAME varchar(15),
CUS_INITIAL varchar(1),
CUS_AREACODE varchar(3),
CUS_PHONE varchar(8),
CUS_BALANCE float(8)
);
ALTER TABLE CUSTOMERDIM
	ADD CONSTRAINT PK_CUSTOMERDIM PRIMARY KEY (CUS_CODE)
ALTER TABLE CUSTOMERDIM
	ADD CONSTRAINT FK_CUS_CODE FOREIGN KEY (CUS_CODE) REFERENCES CHARTER

CREATE TABLE CHARTERDIM (
CHAR_TRIP int NOT NULL IDENTITY,
CHAR_DATE datetime,
AC_NUMBER varchar(5),
CHAR_DESTINATION varchar(3),
CHAR_DISTANCE float(8),
CHAR_HOURS_FLOWN float(8),
CHAR_HOURS_WAIT float(8),
CHAR_FUEL_GALLONS float(8),
CHAR_OIL_QTS integer,
CUS_CODE int
);
ALTER TABLE CHARTERDIM
	ADD CONSTRAINT PK_CHARTERDIM PRIMARY KEY (CHAR_TRIP)
ALTER TABLE CHARTERDIM
	ADD CONSTRAINT FK_AC_NUMBER FOREIGN KEY (AC_NUMBER) REFERENCES AIRCRAFT

CREATE TABLE EMPLOYEEDIM (
EMP_NUM int NOT NULL IDENTITY,
EMP_TITLE varchar(4),
EMP_LNAME varchar(15),
EMP_FNAME varchar(15),
EMP_INITIAL varchar(1),
EMP_DOB datetime,
EMP_HIRE_DATE datetime
);
ALTER TABLE EMPLOYEEDIM
	ADD CONSTRAINT PK_EMPLOYEEDIM PRIMARY KEY (EMP_NUM)
ALTER TABLE EMPLOYEEDIM
	ADD CONSTRAINT FK_EMP_NUM FOREIGN KEY (EMP_NUM) REFERENCES PILOT

CREATE TABLE AIRCRAFTDIM (
AC_NUMBER varchar(5) NOT NULL,
MOD_CODE varchar(10) NOT NULL,
AC_TTAF float(8),
AC_TTEL float(8),
AC_TTER float(8)
);
ALTER TABLE AIRCRAFTDIM
	ADD CONSTRAINT PK_AIRCRAFTDIM PRIMARY KEY (AC_NUMBER)
ALTER TABLE AIRCRAFTDIM
	ADD CONSTRAINT FK_MOD_CODE FOREIGN KEY (MOD_CODE) REFERENCES MODEL

CREATE TABLE PILOTDIM (
EMP_NUM int NOT NULL IDENTITY,
PIL_LICENSE varchar(25),
PIL_RATINGS varchar(25),
PIL_MED_TYPE varchar(1),
PIL_MED_DATE datetime,
PIL_PT135_DATE datetime
);
ALTER TABLE PILOTDIM
	ADD CONSTRAINT PK_PILOTDIM PRIMARY KEY (EMP_NUM)
ALTER TABLE PILOTDIM
	ADD CONSTRAINT FK_EMP_NUM FOREIGN KEY (EMP_NUM) REFERENCES CHARTER_FACT

CREATE TABLE MODELDIM (
MOD_CODE varchar(10) NOT NULL,
MOD_MANUFACTURER varchar(15),
MOD_NAME varchar(20),
MOD_SEATS float(8),
MOD_CHG_MILE float(8)
);
ALTER TABLE MODELDIM
	ADD CONSTRAINT PK_MODELDIM PRIMARY KEY (MOD_CODE)
ALTER TABLE MODELDIM
	ADD CONSTRAINT FK_MOD_CODE FOREIGN KEY (MOD_CODE) REFERENCES CHARTER_FACT

CREATE TABLE CHARTER_FACT (
TIME_ID	int NOT NULL IDENTITY,
MOD_CODE int NOT NULL,
EMP_NUM int NOT NULL,
TOTAL_CHAR_HOURS int,
TOT_FUEL float(8),
REVENUE MONEY
);
ALTER TABLE CHARTER_FACT
	ADD CONSTRAINT PK_CHARTER_FACT PRIMARY KEY (TIME_ID)
ALTER TABLE CHARTER_FACT
	ADD CONSTRAINT PK_EMP_NUM FOREIGN KEY (EMP_NUM) REFERENCES EMPLOYEE

CREATE TABLE STAGING (
	TIME_ID INT,
	MOD_CODE INT,
	EMP_NUM INT,
	CUS_CODE INT,
	TOTAL_CHAR_HOURS INT,
	AC_NUMBER INT,
	CHAR_TRIP INT,
	TOT_FUEL FLOAT(8),
	REVENUE MONEY)
	