--Create A10 procedure

CREATE PROCEDURE A10
AS
BEGIN

--DROP PK AND FK FOR ALL TABLES
ALTER TABLE CUSTOMERDIM
	DROP CONSTRAINT PK_CUS_CODE
ALTER TABLE CUSTOMERDIM
	DROP CONSTRAINT FK_CUS_CODE
ALTER TABLE CHARTERDIM
	DROP CONSTRAINT PK_CHARTERDIM
ALTER TABLE CHARTERDIM
	DROP CONSTRAINT FK_AC_NUMBER
ALTER TABLE EMPLOYEEDIM
	DROP CONSTRAINT PK_EMPLOYEEDIM
ALTER TABLE EMPLOYEEDIM
	DROP CONSTRAINT FK_EMP_NUM
ALTER TABLE AIRCRAFTDIM
	DROP CONSTRAINT PK_AIRCRAFTDIM
ALTER TABLE AIRCRAFTDIM
	DROP CONSTRAINT FK_MOD_CODE
ALTER TABLE PILOTDIM
	DROP CONSTRAINT PK_PILOTDIM
ALTER TABLE PILOTDIM
	DROP CONSTRAINT FK_EMP_NUM
ALTER TABLE MODELDIM
	DROP CONSTRAINT PK_MODELDIM
ALTER TABLE MODELDIM
	DROP CONSTRAINT FK_MOD_CODE
ALTER TABLE CHARTER_FACT
	DROP CONSTRAINT PK_CHARTER_FACT
ALTER TABLE CHARTER_FACT
	DROP CONSTRAINT PK_EMP_NUM

--TRUNCATE TABLES
TRUNCATE TABLE CUSTOMERDIM
TRUNCATE TABLE CHARTERDIM
TRUNCATE TABLE AIRCRAFTDIM
TRUNCATE TABLE EMPLOYEEDIM
TRUNCATE TABLE PILOTDIM
TRUNCATE TABLE CHARTER_FACT
TRUNCATE TABLE MODELDIM
TRUNCATE TABLE STAGING

--RE-ADD CONSTRAINTS
ALTER TABLE CUSTOMERDIM
	ADD CONSTRAINT PK_CUSTOMERDIM PRIMARY KEY (CUS_CODE)
ALTER TABLE CUSTOMERDIM
	ADD CONSTRAINT FK_CUS_CODE FOREIGN KEY (CUS_CODE) REFERENCES CHARTER
ALTER TABLE CHARTERDIM
	ADD CONSTRAINT PK_CHARTERDIM PRIMARY KEY (CHAR_TRIP)
ALTER TABLE CHARTERDIM
	ADD CONSTRAINT FK_AC_NUMBER FOREIGN KEY (AC_NUMBER) REFERENCES AIRCRAFT
ALTER TABLE EMPLOYEEDIM
	ADD CONSTRAINT PK_EMPLOYEEDIM PRIMARY KEY (EMP_NUM)
ALTER TABLE EMPLOYEEDIM
	ADD CONSTRAINT FK_EMP_NUM FOREIGN KEY (EMP_NUM) REFERENCES PILOT
ALTER TABLE AIRCRAFTDIM
	ADD CONSTRAINT PK_AIRCRAFTDIM PRIMARY KEY (AC_NUMBER)
ALTER TABLE AIRCRAFTDIM
	ADD CONSTRAINT FK_MOD_CODE FOREIGN KEY (MOD_CODE) REFERENCES MODEL
ALTER TABLE PILOTDIM
	ADD CONSTRAINT PK_PILOTDIM PRIMARY KEY (EMP_NUM)
ALTER TABLE PILOTDIM
	ADD CONSTRAINT FK_EMP_NUM FOREIGN KEY (EMP_NUM) REFERENCES CHARTER_FACT
ALTER TABLE MODELDIM
	ADD CONSTRAINT PK_MODELDIM PRIMARY KEY (MOD_CODE)
ALTER TABLE MODELDIM
	ADD CONSTRAINT FK_MOD_CODE FOREIGN KEY (MOD_CODE) REFERENCES CHARTER_FACT
ALTER TABLE CHARTER_FACT
	ADD CONSTRAINT PK_CHARTER_FACT PRIMARY KEY (TIME_ID)
ALTER TABLE CHARTER_FACT
	ADD CONSTRAINT PK_EMP_NUM FOREIGN KEY (EMP_NUM) REFERENCES EMPLOYEE

--INSERT DATA FROM ORIGINAL DATABASE
INSERT INTO CUSTOMERDIM
	SELECT *
	FROM CUSTOMER

INSERT INTO CHARTERDIM
	SELECT *
	FROM CHARTER

INSERT INTO EMPLOYEEDIM
	SELECT *
	FROM EMPLOYEE

INSERT INTO AIRCRAFTDIM
	SELECT *
	FROM AIRCRAFT

INSERT INTO PILOTDIM
	SELECT *
	FROM PILOT

INSERT INTO MODELDIM
	SELECT *
	FROM MODEL

INSERT INTO CHARTER_FACT
	SELECT	C.CHAR_HOURS_FLOWN, C.CHAR_FUEL_GALLONS, (C.CHAR_FUEL_GALLONS * M.MOD_CHG_MILE) AS REVENUE
	FROM	CHARTER C INNER JOIN AIRCRAFT A ON C.AC_NUMBER = A.AC_NUMBER INNER JOIN
			MODEL M ON A.MOD_CODE = M.MOD_CODE

INSERT INTO STAGING
	SELECT	C.CUS_CODE, CH.CHAR_TRIP, A.AC_NUMBER, E.EMP_NUM, P.EMP_NUM, CF.TIME_ID, CF.TOT_CHAR_HOURS, CF.TOT_FUEL, CF.REVENUE, M.MOD_NUM
	FROM	CUSTOMER C INNER JOIN CHARTER CH ON C.CUS_CODE = CH.CUS_CODE INNER JOIN
			AIRCRAFT A ON CH.AC_NUMBER = A.AC_NUMBER INNER JOIN
			MODEL M ON A.MOD_CODE = M.MOD_CODE INNER JOIN
			CHARTER_FACT CF ON M.MOD_CODE = CF.MOD_CODE INNER JOIN
			PILOT P ON CF.EMP_NUM = P.EMP_NUM INNER JOIN
			EMPLOYEE E ON E.EMP_NUM = P.EMP_NUM INNER JOIN

--UPDATE STAGING TABLE WITH DIMENSION TABLE PK INFO
UPDATE	STAGING
SET		CUS_CODE = D.CUS_CODE
FROM	STAGING S INNER JOIN CUSTOMERDIM D
		ON S.CUS_CODE = D.CUS_CODE

UPDATE	STAGING
SET		CHAR_TRIP = CH.CHAR_TRIP
FROM	STAGING S INNER JOIN CHARTERDIM CH
		ON S.CHAR_TRIP = CH.CHAR_TRIP

UPDATE	STAGING
SET		AC_NUMBER = A.AC_NUMBER
FROM	STAGING S INNER JOIN AIRCRAFT A
		ON S.AC_NUMBER = A.AC_NUMBER

UPDATE	STAGING
SET		EMP_NUM = E.EMP_NUM
FROM	STAGING S INNER JOIN EMPLOYEE E
		ON S.EMP_NUM = E.EMP_NUM

UPDATE	STAGING
SET		TIME_ID = CF.TIME_ID
FROM	STAGING S INNER JOIN CHARTER_FACT CF
		ON S.TIME_ID = CF.TIME_ID

UPDATE	STAGING
SET		TOTAL_CHAR_HOURS = CF.TOTAL_CHAR_HOURS
FROM	STAGING S INNER JOIN CHARTER_FACT CF
		ON S.TOTAL_CHAR_HOURS = CF.TOTAL_CHAR_HOURS

UPDATE	STAGING
SET		REVENUE = CF.REVENUE
FROM	STAGING S INNER JOIN CHARTER_FACT CF
		ON S.REVENUE = CF.REVENUE

UPDATE	STAGING
SET		MOD_CODE = M.MOD_CODE
FROM	STAGING S INNER JOIN MODEL M
		ON S.MOD_CODE = M.MOD_CODE

--INSERT DW KEYS AND FACTS INTO CHARTER_FACT TABLE
INSERT INTO CHARTER_FACT (TIME_ID, MOD_CODE, EMP_NUM, TOTAL_CHAR_HOURS, TOT_FUEL, REVENUE)
	SELECT	TIME_ID, MOD_CODE, EMP_NUM, TOTAL_CHAR_HOURS, TOT_FUEL, REVENUE
	FROM	STAGING

END

--RUN STORED PROCEDURE
EXEC A10

SELECT	*
FROM	STAGING